snekasbiddjangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from sneaksbid import views
from django.contrib.auth import views as auth_views
from sneaksbid.views import HomeView, shop, ShoeCreateView, CheckoutView, add_to_cart, view_cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
    path('signup', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('shop/', views.shop, name='shop'),
    path('item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('item/<int:item_id>/bid/', views.place_bid, name='place_bid'),
    path('payment/', views.process_payment, name='process_payment'),
    path('add-shoe/', ShoeCreateView.as_view(), name='add_shoe'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('search/', views.search_sneakers, name='search_sneakers'),
    path('user_history/', views.user_history, name='user_history'),
    # path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    # path('checkout/success/', checkout_success_view, name='checkout_success'),
    path('about/', views.aboutus, name='about'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('view-cart/', views.view_cart, name='view_cart'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #  path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_cart'),
    path('payment/<total_winning_bid>/', views.process_payment, name='process_payment'),
    path('contact/', views.contactus, name='contact'),

    path('payment_success/', views.payment_success, name='payment_success'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sneaksbid/forms.py
from datetime import timedelta
from decimal import Decimal
from django.contrib.auth.forms import UserChangeForm
from .models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Payment2, Bid, Shoe, Brand


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class SignInForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter Your Username',
        'id': 'username',
        'required': True
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter Your Password',
        'id': 'password',
        'required': True}))


class PaymentForm(forms.Form):
    amount = forms.DecimalField(
        decimal_places=2,
        max_digits=10,
        widget=forms.HiddenInput()
    )


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['bid_amount']
        widgets = {
            'bid_amount': forms.NumberInput(attrs={'step': '0.01', 'min': '0'}),
        }

    def __init__(self, *args, **kwargs):
        self.item = kwargs.pop('item', None)
        super(BidForm, self).__init__(*args, **kwargs)
        if self.item:
            self.fields['bid_amount'].widget.attrs['min'] = str(self.item.base_price + Decimal('0.01'))


class ShoeForm(forms.ModelForm):
    auction_duration_days = forms.IntegerField(min_value=0, initial=0, help_text='Days', required=False)
    auction_duration_hours = forms.IntegerField(min_value=0, max_value=23, initial=0, help_text='Hours', required=False)
    auction_duration_minutes = forms.IntegerField(min_value=0, max_value=59, initial=0, help_text='Minutes',
                                                  required=False)

    class Meta:
        model = Shoe
        fields = ['title', 'description', 'base_price', 'brand_name', 'image', 'size']

    def save(self, commit=True):
        days = self.cleaned_data.get('auction_duration_days', 0)
        hours = self.cleaned_data.get('auction_duration_hours', 0)
        minutes = self.cleaned_data.get('auction_duration_minutes', 0)

        total_duration = timedelta(days=days, hours=hours, minutes=minutes)

        self.instance.auction_duration = total_duration

        return super(ShoeForm, self).save(commit=commit)


class UserUpdateForm(UserChangeForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['images']


PAYMENT_CHOICES = [
    ('S', 'Stripe'),

]


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite',
        'class': 'form-control'
    }))
    country = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Country',
        'class': 'form-control'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Zip code',
        'class': 'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CartItemForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1)


class ShoePriceRangeForm(forms.Form):
    minimum_price = forms.IntegerField(label='Minimum price', min_value=0, required=False)
    maximum_price = forms.IntegerField(label='Maximum price', min_value=0, required=False)

    def clean(self):
        cleaned_data = super().clean()
        minimum_price = cleaned_data.get('minimum_price')
        maximum_price = cleaned_data.get('maximum_price')

        if minimum_price and maximum_price and minimum_price > maximum_price:
            raise forms.ValidationError("Minimum price cannot be greater than maximum price")
        return cleaned_data

class BrandFilterForm(forms.Form):
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), label='Select Brand', required=False)


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ['name']
        widgets = {'name': forms.TextInput (attrs={'placeholder':'Enter A New Brand', 'class':'form-control'})}

    def clean_name(self):
        name = self.cleaned_data.get('name')

        # Check if a brand with the same name already exists
        if Brand.objects.filter(name=name).exists():
            raise forms.ValidationError("Brand with this name already exists.")

        return name

sneaksbid/views.py
from django.urls import reverse_lazy
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View, CreateView
from sneaksbid.models import Item, Bid, OrderItem
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import EmailMessage, send_mail
from snekasbiddjangoProject import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth import authenticate, login, logout
from .tokens import generate_token
from decimal import Decimal
from django.conf import settings
from .forms import SignUpForm, ShoeForm
from .forms import SignInForm, CheckoutForm
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import PaymentForm, BidForm, Bid
from .models import Payment2, Shoe, Order, BillingAddress, Bid, Brand
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import Item
from django.db.models import F
from django.utils import timezone
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from .forms import ShoePriceRangeForm, BrandFilterForm

class HomeView(ListView):
    template_name = "./sneaksbid/homepage.html"
    context_object_name = 'items'
    ordering = ['-bid_expiry']

    def get_queryset(self):
        return Item.objects.all()

    def dispatch(self, request, *args, **kwargs):

        if 'visit_count' in request.session:
            request.session['visit_count'] += 1
        else:
            request.session['visit_count'] = 1

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['visit_count'] = self.request.session['visit_count']
        return context

def user_history(request):

    search_history = request.session.get('search_history', [])

    visit_count = request.session.get('visit_count', 0)
    
    context = {
        'visit_count': visit_count,
        'search_history': search_history,
    }
    return render(request, 'sneaksbid/user_history.html', context)

def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                fname = user.first_name

                return render(request, "authentication/index.html", {"fname": fname})
            else:
                messages.error(request, "Bad Credentials!!")
                return redirect('home')
    else:
        form = SignInForm()
    return render(request, "authentication/signin.html", {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')

            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already exists! Please try some other username.")
                return redirect('home')

            if User.objects.filter(email=email).exists():
                messages.error(request, "Email Already Registered!!")
                return redirect('home')

            if password1 != password2:
                messages.error(request, "Passwords didn't match!!")
                return redirect('home')

            user = form.save(commit=False)
            user.first_name = first_name
            user.last_name = last_name
            user.is_active = False
            user.save()


            subject = "Welcome to SneaksBid Login!!"
            message = "Hello " + user.first_name + "!! \n" + "Welcome to SneaksBid!! \nThank you for visiting our website.\nWe have also sent you a confirmation email, please confirm your email address.\n\nThanking You\n"
            from_email = settings.EMAIL_HOST_USER
            to_list = [user.email]
            send_mail(subject, message, from_email, to_list, fail_silently=True)


            current_site = get_current_site(request)
            email_subject = "Confirm your Email @ SneaksBid Login!!"
            message2 = render_to_string('email_confirmation.html', {
                'name': user.first_name,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': generate_token.make_token(user)
            })
            email = EmailMessage(
                email_subject,
                message2,
                settings.EMAIL_HOST_USER,
                [user.email],
            )
            email.fail_silently = True
            email.send()

            messages.success(request,
                             "Your Account has been created successfully! Please check your email to confirm your email address in order to activate your account.")
            return redirect('signin')
        else:

            messages.error(request, "Error processing your form.")
    else:
        form = SignUpForm()
    return render(request, 'authentication/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        login(request, myuser)
        messages.success(request, "Your Account has been activated!!")
        return redirect('signin')
    else:
        return render(request, 'activation_failed.html')


def signout(request):
    logout(request)
    messages.success(request, "Logged Out Successfully!!")
    return redirect('home')


def shop(request):
    sneakers = Item.objects.all()
    brands = Brand.objects.all()

    form1 = ShoePriceRangeForm(request.GET)
    form2 = BrandFilterForm(request.GET)

    if form1.has_changed():
        if form1.is_valid():
            minimum_price = form1.cleaned_data['minimum_price']
            maximum_price = form1.cleaned_data['maximum_price']
            filtered_products = Item.objects.filter(base_price__range=(minimum_price, maximum_price))

            return render(request, 'sneaksbid/shop.html', {'sneakers': filtered_products, 'form1': form1, 'form2': form2, 'brands': brands})

    if form2.has_changed():
        if form2.is_valid():
            selected_brand = form2.cleaned_data['brand']
            filtered_products = Item.objects.filter(brand_name=selected_brand)

            return render(request, 'sneaksbid/shop.html',{
                          'sneakers': filtered_products, 'form1': form1, 'form2': form2, 'brands': brands})

    context = {
        'sneakers': sneakers,
        'brands': brands,
        'form1': form1,
        'form2': form2
    }

    return render(request, 'sneaksbid/shop.html', context)


def search_sneakers(request):
    query = request.GET.get('query')
    search_results = Item.objects.filter(title__icontains=query)
    search_history = request.session.get('search_history', [])
    search_history.append(query)
    request.session['search_history'] = search_history
    
    return render(request, 'sneaksbid/search_result.html', {'search_results': search_results})


def item_detail(request, item_id):

    item = get_object_or_404(Item, pk=item_id)
    is_auction_active = item.is_auction_active
    winning_bid = item.bids.filter(is_winner=True).first()
    last_10_bids = item.bids.all().order_by('-bid_time')[:10]

    context = {
        'item': item,
        'is_auction_active': is_auction_active,
        'winning_bid': winning_bid,
        'last_10_bids': last_10_bids,

    }

    return render(request, 'sneaksbid/item_detail.html', context)


@login_required
def place_bid(request, item_id):
    item = get_object_or_404(Item, id=item_id)

    if not item.available:
        messages.error(request, "The item is not available.")
        return redirect('item_detail', item_id=item.id)

    user_won_auction = False

    if request.method == 'POST':
        form = BidForm(request.POST, item=item)
        if form.is_valid():
            bid_amount = form.cleaned_data['bid_amount']
            last_bid = item.bids.order_by('-bid_amount').first()
            if last_bid and bid_amount <= last_bid.bid_amount:
                messages.error(request, "Your bid must be higher than the current highest bid.")
                return redirect('place_bid', item_id=item.id)
            elif bid_amount <= item.base_price:
                messages.error(request, "Your bid must be higher than the base price.")
                return redirect('place_bid', item_id=item.id)

            bid = form.save(commit=False)
            bid.item = item
            bid.user = request.user
            bid.save()


            previous_winner = item.bids.filter(is_winner=True).first()
            if previous_winner:

templates/sneaksbid/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "./header.html" %}
    <title>{% block head_title %}{% endblock head_title %}</title>
    {% block extra_head %}{% endblock extra_head %}
    <style type="text/css">
      .form-control {
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da !important;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
      }
    </style>
  </head>
  <body>
    {% include "./nav.html" %}

    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
    </div>

  {% block content %}{% endblock content %}
  {% block extra_body %}{% endblock extra_body %}
  {% include "./footer.html" %}
  {% include "./script.html" %}
  {% block extra_scripts %}{% endblock extra_scripts %}
  </body>
</html>

templates/sneaksbid/checkout.html
{% extends './base.html' %}
 {% load static %}
{% block content %}
<style>
    .checkout-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        border-radius: 10px;
        text-align: center;
    }
 .form-field {
        margin-bottom: 15px;
    }

    .form-field label {
        display: block;
        margin-bottom: 5px;
    }

    .form-field input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ddd;
        border-radius: 4px;
    }
    .checkout-container h2 {
        color: #333;
        margin-bottom: 20px;
    }

    .checkout-container form {
        display: flex;
        flex-direction: column;
    }

    .checkout-container label {
        text-align: left;
        margin: 10px 0 5px;
    }

    .checkout-container input[type="text"],
    .checkout-container input[type="submit"] {
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .checkout-container input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        cursor: pointer;
    }

    .checkout-container input[type="submit"]:hover {
        background-color: #45a049;
    }

    .checkout-container .alert-danger {
        background-color: #f8d7da;
        color: #721c24;
        padding: 10px;
        margin-top: 10px;
        border-radius: 5px;
        border: 1px solid #f5c6cb;
    }

    .checkout-container ul {
        list-style-type: none;
        padding: 0;
    }
  .payment-options {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        margin-bottom: 20px;
    }

    /* Style for each payment option label */
    .payment-option-label {
        display: flex;
        align-items: center;
        margin: 5px 0;
    }

    /* Style for the radio buttons */
    .payment-option-label input[type="radio"] {
        margin-right: 10px;
    }

    /* Style for the payment option images */
    .payment-option-label img {
        height: 20px;
        margin-right: 10px;
    }

    /* Style for the submit button */
    .submit-button {
        width: 100%;
        height: 40px;
        margin-top: 20px;
        font-size: 16px;
    }
</style>
<div class="checkout-container">
    <h2>Checkout</h2>
    <form method="post">
        {% csrf_token %}
         {{ form.non_field_errors }}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {% if field.name != 'payment_option' %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endif %}
        {% endfor %}

        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <!-- Display winning bid details -->
    <div>
        {% if bid.is_winner == 'True' %}
            <p>Item: {{ bid.item.title }}</p>
            <p>Final Winning Bid: {{ bid.bid_amount }}</p>
        {% endif %}
    </div>
      <div class="payment-options">
            <div class="payment-option-label">
                <input type="radio" id="id_payment_option_0" name="payment_option" value="S">
                <label for="id_payment_option_0">
                    <img src="{% static 'images/stripe.png' %}" alt="Stripe">
                    Stripe
                </label>
            </div>
        </div>
        <input type="submit" value="Proceed to Payment" class="submit-button">
    </form>
</div>

{% endblock %}

templates/sneaksbid/search_result.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
.sneaker-images {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around; /* Adjust alignment of items */
    }
.btn {
        background-color: #000;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        text-align: center;
        width: 50%; /* Allow the button to size according to its content */
        margin-top: auto; /* Pushes the button to the bottom of the card */
    }
   .btn:hover {
        background-color: #333;
    }

.sneaker {
	width: calc(25% - 20px); /* Set width for each sneaker container */
	margin-bottom: 20px; /* Add some space between sneakers */
	text-align: center; /* Center align content */
	position: relative; /* Position relative for absolute positioning of overlay */
}

.sneaker img {
	width: 100%; /* Make the image fill the container width */
	height: auto; /* Maintain aspect ratio */
	max-height: 200px; /* Set maximum height */
	transition: transform 0.3s; /* Add transition for smooth effect */
}

.sneaker h3 {
	margin-top: 10px; /* Add margin to top of title */
}

.sneaker:hover img {
    transform: scale(1.1); /* Scale up the image on hover */
}

.sneaker-overlay {
    position: absolute; /* Position absolute for overlay */
    top: 0; /* Align overlay to the top */
    left: 0; /* Align overlay to the left */
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    background-color: rgba(246, 242, 242, 0); /* Semi-transparent black background */
    opacity: 0; /* Initially hidden */
    transition: opacity 0.3s; /* Add transition for smooth effect */
    display: flex; /* Use flexbox for centering */
    justify-content: center; /* Center horizontally */
    align-items: center; /* Center vertically */
}

.sneaker:hover .sneaker-overlay {
    opacity: 1; /* Show overlay on hover */
}

.sneaker p {
	margin-bottom: 5px; /* Add margin to bottom of paragraphs */
}

.sneaker .btn {
	margin-top: 10px; /* Add margin to top of button */
}
.search-form {
	margin-bottom: 20px;
	text-align: center;
}

input[type='text'], input[type='number'], input[type='password']{
    border: 1px solid #cecece !important;
    margin-bottom: 5px;
}

.search-input {
	padding: 8px;
	border-color:   #4CAF50;
	border-radius: 4px;
	margin-right: 5px;
	margin-top: 10px;
    border: 1px solid #cecece !important;
}

.search-button {
	padding: 8px 16px;
	/* border: none; */
	background-color: #4CAF50;
    border: 1px solid #4CAF50;
	color: white;
    border-radius: 0 4px 4px 0;
	border-radius: 4px;
	cursor: pointer;
    margin-left: -5px;
}

.search-button:hover {
	background-color: #45a049;
}

#brand_filter_button,
#search_price_button{
    padding: 8px 16px;
    border: none;
    background-color: #4CAF50;
    border: 1px solid #4CAF50;
    color: white;
    border-radius: 4px;
    margin-top: 5px;
}

#id_brand{
    padding: 8px;
    border: 1px solid #cecece;
    border-radius: 4px;
    width: 40%;
}
</style>

</head>
<body>
    <!-- Title Page -->
    <section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/static/images/sneaksbid.jpg);">
        <h2 class="l-text2 t-center">
            Shop
        </h2>
        <p class="m-text13 t-center">
            All categories
        </p>
    </section>

    <!-- Search Bar -->
    <form action="{% url 'search_sneakers' %}" method="GET" class="search-form">
        <input type="text" name="query" placeholder="Search shoes by name" class="search-input">
        <button type="submit" class="search-button">Search</button>
    </form>

    <!-- Display Search Results -->
    <div class="sneaker-images">
        {% if search_results %}
            {% for sneaker in search_results %}
            <div class="sneaker">
                <img src="{{ sneaker.image.url }}" alt="{{ sneaker.title }}">
                <h3>{{ sneaker.title }}</h3>
                <p>Description: {{ sneaker.description }}</p>
                <p>Price: ${{ sneaker.base_price }}</p>
                {% if sneaker.is_auction_active %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'place_bid' item_id=sneaker.id %}" class="btn btn-primary">Place Bid</a>
                    <p>Auction is active!</p>
                    {% endif %}
                        <div id="auction-timer-{{ sneaker.id }}" class="auction-timer" data-end-time="{{ sneaker.post_time|date:'c' }}" data-duration-seconds="{{ sneaker.auction_duration.total_seconds }}">
        Auction ends in approximately {{ item.duration_days }} days, {{ item.duration_hours }} hours, {{ item.duration_minutes }} mins
    </div>
                {% else %}
                    <p>Auction is not active.</p>
                            <a href="{% url 'place_bid' item_id=sneaker.id %}" class="btn btn-primary">View Bid</a>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
            <p>No search results found.</p>
        {% endif %}
    </div>
        <script>
document.addEventListener('DOMContentLoaded', function() {
    const timers = document.querySelectorAll('.auction-timer');

    timers.forEach(function(timer) {
        const endTime = new Date(timer.getAttribute('data-end-time')).getTime();
        const durationSeconds = parseInt(timer.getAttribute('data-duration-seconds'), 10);
        const auctionEndTime = endTime + (durationSeconds * 1000);

        const updateCountdown = () => {
            const now = new Date().getTime();
            const timeLeft = auctionEndTime - now;

            if (timeLeft < 0) {
                timer.innerHTML = "Auction ended";
                clearInterval(interval); // Stop updating when the auction ends
                return;
            }

            // Calculate days, hours, minutes, and seconds
            let days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
            let hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            let minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
            let seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);

            // Update the timer's content
            timer.innerHTML = `Auction ends in approximately ${days}d ${hours}h ${minutes}m ${seconds}s`;
        };

        // Update the countdown every second
        updateCountdown(); // Update immediately to avoid delay
        const interval = setInterval(updateCountdown, 1000);
    });
});
</script>
{% endblock content %}